const ENTER_KEY = 13;

const KEY_0 = 48;
const KEY_1 = 49;
const KEY_2 = 50;
const KEY_3 = 51;
const KEY_4 = 52;
const KEY_5 = 53
const KEY_6 = 54;

const M_KEY = 77;
const P_KEY = 80;
const S_KEY = 83;

let gStartX = 0;
let gBlockSize = 60;
let gScale = 1.0;
let gScreenX = 400;
let gScreenY = 600;

let cvs;
let canvas;

let bufCanvas;
let bufCtx;

let daisyGame;
let drawEngine;
let gameEngine;
let scoreDB;

let offset = 0;
let isMobile = false;

let LoadImage = function (image_name) {
  let load_image = new Image();
  load_image.src = image_name;
  return load_image;
}

const pop_sound = "//vQxAAAKCmlGnW8gA6fxKWnPbAAAAILNOBdzY0cMRzCiYzg+M+NjLCAxgWMcHDMSsycdMRA1Y660y5a6jCB" +
    "Y9dTxlNUNaRhFGcgZxCBhec0lDQGVAremHAy5GaICzMMASDepfpFveyhpi0zCCLoQyu+FJUAAIIAY2YxAGIaA4bjvAkIkRCWGMQild22d" +
    "uXL9Q2w9U7B4KL2GAAkgFwTKKARjQHDdduCEhHx6Syhdh7Ibi8ALCNMVXMQYDELUkrlxeYfyWW8/3K3/ct378rp+3XDUDRXYO3AtmgDYP" +
    "L6d92tsPXepo4lWN0zAExHNBoJZAuw2j7s7futLLr+UUNuXD807EmYGXIRQdSPuW79+kliw5dcwxTFFBQbnq2JgQKsI2jxpforpFrrZ2s" +
    "Og4oI6lC7bluWw9Y6KiKiDiKigjEHcfx/HLd/MPDw8AAAAAAw8PDx4AACAAEgAAAQQFgWzDwQfOAV08wgh0zLCPTMV8O0wQx4TPHDzNQI" +
    "z4z0lgzTSTzMfwzMzg3qjCOCRMUAT4wMQATBQAAM6ISYwQgSzTPI2YzMhZDPyh9YBOfhTuDM2szHS0wdIM7BnWeyJmRkZmbGYEhBchMGF" +
    "wcAtLSucl22voggQVMwagIagN1JpsGEo4HGWnQNBh4DMRBGDIaIRuQTGBtAwYyZkxmgRABkKp5oaEZOCRpBC6plBiXvaZSyWKmADpmQyV" +
    "BgxsvAJmSmgGMWhGRiZggeYkKqqp0gUYbLB8NVY9hwHXpMLylWYqhpQNhA0DhkmF1oKxOSqsW+GRNVQBCUHymBoGjbdIxKm3gIQASpWrh" +
    "wMZEJGBiZgQGIAJTNqQcCwZBpblVWDnLg9VVWGDEVqaAozT0EbprkulzdjSzcsBqKAKF0VwYFIJ1wqog4XY2vtBcHDfixUzlnKRr4s4FQ" +
    "b2dJGs5BASCAdnL5P+/zTn/bO/jZ5K2VdrSPXfJpL///////////////////tV///2qf/+1VqrVv///////////6GM/9DR/Q0aoyJUnSM" +
    "EgBIDHRQ5UyAMr2MChHRDK9xogxnkYIMIVHWCwPkGN0AKhg/IxIaEu+bn9FGNZmNRB6ViCBgKQJoYNKBhGApP/70sQiA/OpkQId/gAGQr" +
    "Rfwf5pkA0p6UpGwimVlM5qUjHA5K0iaQHJjlzGwymZSKZlIpFgpmUimYlEvmJBKWBKYkEpiQSlYlLBpM0CUrEhiUSmJBKYkEpmgS+VlMr" +
    "KXmUin5lIplgpeVlIrHJpAcmORyY4SBpFIGkRx5jkcGkEiWBwY5HBUHBWFywFywF/LAWLAXKwsWAsWCUYWC5WSjCwXMLBcwuFzC4XLAWK" +
    "wsZIC5ksLlgLlgLeVhcwuFvMLBfzCwXMLBYwsSTC5KMLkowsFzCwWKwt5WF/LAX/zC4W/ywF/KwuYXCxhcLGFwv/lYlKxJ5YEnlgSGJBJ" +
    "5WJTEgkKxJ5YEpiQSmJBKWBIViQrEhYEpWJfKxIViQrEn//////lgS+ViQxIJCsSFgSlYk8sCT/KxL/+UE4xKJf//LA48rHH/5WOP8xyO" +
    "CwODHI4KxyY4HJjgcmORwWBwWBxzywOSwOfKxyY4HJWOPu+4xKgHUMCZFMCwHgmCvCeJg+Y7kYTQBmGAlj9hjSIh8YakKxGAsAhBpqxHu" +
    "aAwcTnSxHuZglwZAYJeDqmul0a7ahtWSFgZmMl2YYJ5mhPlpDGaEMnmgzQMjZMzZGANmOdPNkYNCgUaCow0IwKDTajTnT02AIZAhlAo9D" +
    "Mr0lgwBmQFMGZZlgwBsxmTBaU5zIDMgKzAphAs2TMsGAOfAzArMGYZmzMFc82ZgsGP/ywQ/ywRKyHlZEyOo3pAsPDekDGS0VAoMNu1Cg0" +
    "IMqNqcmNGBRCWBhYahUYiuo0iuFRgdGDgip1SqlDgqpiwDMEDKwRYBqlMGCEINUohBCAGWARkwapA4P4QaCqAINBQYFRgQa9FdFY0IwKo" +
    "EVlOAoNU5KxgQaMaMCowKDSwNCg1FZRosGU2f8rMlpvLToFpsFpDMGTMGQMzAplAstKmwWnTZAhn/TYTY9Nn0Cy0pacDMU2PLTlpy0ibC" +
    "BZYMlpQIYLNGZMAZkBmJaUrMgbMBmQFMeBDPpsJsoFf6BSbKBSBYFMAUxBAzogL5MHRBCjAHBokxAIMZMLcFPTF1RYgwogM/MIDCAjC4g" +
    "0owT4JXML5DWjL11Xk0TwO9MIzCMjBCgQsxkyNo8TaZ4//vSxCKCME2i+i/vLIaPNF5h7emAzMYO7TzhE8DhBkK8EN6nBkBqWIDggMzQK" +
    "6HtuKkmQqKwgghJIVJRVCQUVCwaZph77BU0KwqlVIaYZhBlgIrSNJIw0jjCOMI04zSSaoHTGmmYQRhpCFIQJnnGVhNVVO1YQBCANUjVCw" +
    "GHCGGmYSQdMHDiEJqpaUrZQKA84GwK2UCjZZLSoEgNggUBsCtgsMoFlp/MMI00hAmHSlYbVxAGqYrDauWAmqNWVMWAlSmGkHThwhhhIrq" +
    "cKNqNeit5WYWDAob5mmFZqKhmGhDCjQQypyFDQqao2ZhqKgVM9NlNhAtNgtKWkLSoFARkDYmwyWlLSgVgCsf5aVAstMWmLSoFlm02f9Ff" +
    "1GkV0VjMNPQ0rMKzEVVGywYFTDNNRVMw0IYCppwQhIAQ0ENorKcIrBIajf+pwpwo0pyo0iuENIrCRVBz0KkmRmLaaPSEBkulbmUELuYu5" +
    "oBjqh5GcwmuYPbXBrEFuGXGjEcMT8ZjcI8mEkNwYhISZwjQBLsrnj6XjlXza9DGNjQ3jQjTGtjlICsIYSUWAp71BqZYVvGgvlgaFBpWMM" +
    "ahKzAGZgZmWmMwzK9BsjIFMm1GorhBs2w0KSjGtzbIQgwY2WFZRacCGUCgMwAzAzBhAsrnAQwc9kBs5aQIhBRCbRCFRgUGGNGBUYo0FWy" +
    "jQUGBEAxowKNxCCEJI2YIwYIrBmCBmTBBwYODGjRKmMGiDoohJNVVN4FMlhkgWBTBaZAsDMi0gFMpsFZhNlNlAvwMwQKMwZTYLTgQyYQK" +
    "VhDCBSsIVhf8woQsBfLAQsBCwEMKFMIEMIp8rCFYQwgUwqkrlGEUlgKakIYQKVqDChDChfMIFLAQsBCwELAQwgUrClYUsBCxLMIEMKpMK" +
    "oMKELCkrUFYUrClgL5hFJhAqbCBZYMgRkWDJaYCGQMyAzBNhNlAssMi0pmTAGyoFJsJsGYMFpy0xYZoFFZkCmCswmwmyWlTYLSoFemwWl" +
    "AhgtOqNdk1MxfRCDA8QhMBA/MxwAnDDGEvMo9EMxGgdDF7W4Mz4D01Y44jDiTiNiEfYwexEzAvDGODXzFWsXBjM0I1IzEIEZlBhIiYYQG" +
    "GpRn/+9LEJoP1lbbsD29Mhgs/nkHcQzipoamWagIe9QYSWagIbJmc9mBGRmWRmTJsp5szBacrZmZZljQBz5mGRmTAQbNCgCDAQaNqMCow" +
    "5aA5YwsNAqMRWCDAUQhBkxgwxqA0Iw0I0sSjGoTQIAqhAzICmS0hmTHlpE2QKZArIsGS0hWzLSlbI2rQKDDGjDGDAjUFRqK3mMGqcBQai" +
    "oWGxYGoqBVCEGQNmLTJslpUCi0ybPgZgBTAEMFpUCvLSgQyZgx5aRAszJg1AUrCmFCGFCeWAphQhYCmFCGECmEC/5hQpYUlgIagKWApWE" +
    "NSFLCk1AUwigrClgIYQKYUIVqCwFLATywFMKo8rCGFCGEUlgKWApYClYU1IQwoU1IUwgUwgQwoUrClYQrCmEUeYUKVhCsKYQL5hAhhApW" +
    "EKwhYClgJ5hVJWFLAQsBSwEMKELAU1AQwoUwoQrUlYQwgU1KgwoUsKDUhPMIF//8woQrUlgL/////+WMR92jBtkIoCN0yKcEyyO8wFKIy" +
    "HnMyZCoxxIkyIpE3MNk7D9c1EM4rHAsAkY9gyYBgEMAeYNAYYNBSYpg0gTLAGtnMGhFEQGruAAGF9QEDICBgAg2YGhQIgoAINlkmyBgZB" +
    "cGQuDAXBksBUYDgMGBmp2bGF+za3wA0voWQXYbNlbF3FkWziJpfosiAsCNqBMRsAOl3uUoyDip6DRk9nJBxU9HJcuDk9iwJTtTwWMVmCx" +
    "1PKeTFU6THU8WDeGMU+mMGxLBiswY1MQzGU6TFTFTF9T6Y6YwY5MZMRTpT4XOGO9RFNsuUXLTbTaUQ8uT5Yl5ckuWm0XITbUQLkFyC5ab" +
    "XqIFyguZTxYMp71PpieWMKdJjep9MRMRMRTv1OlPpiqe8sGU8FzpjqdqfU6U79TvzOdTtMYLmTFU8VmU+mOWDqdJjGcwY4McmMmMmIGOC" +
    "5lOkxkxExPTHTHU+p5TyngNYGgMAYQiBEBiDEGARAi/BhwYAwgwwi4ReDEIgMIRQiwigaga1AAIEQDZdwjPRkzIYNzOhUzWQ4zEUUDNY0" +
    "TMVFjGBOTG0QzPJ4Tk5qzNQ0zLAQDJMAzIATjCMjzDQTjHiNacRhnIceoZyDGiGF8DXTf/70sQmAjPSEPEO5w+FasIbibw9eA9EjhKkEp" +
    "mQMApjRUChZZ5JoiMCByyAVDKiQkUHDFYRhAHKEsQhHFAgsiVAFhQwIQgjYBReCkTIVLAyWqPyNAGRSNJQnLLjGIqYydJIFFcUAmOIRN1" +
    "CBAJLDxIgYkRDUEERXNMRW7LChYKnxCBmalVEkOEdMpHbZ0kal6iwBnN0SjVa19dzW1IJdoiIPoGLrQ5NEQxTmCgVAVAELm6RdrqYzPA5" +
    "SxAE6j4oFbaCx5jiunCp1Bi5rWl1pEBxmxL7Ywo67rntQJBiwFNyQQcZUyaLAlvtWYWvxnqnSmQQKB0FY+0GA2m1ImncsIrUz6Ll/l87W" +
    "ahskNL6ibYOivZVqtSrFuv+spR1jVtFaox5gz4PPGKdeJgCuEGgcB6Uqo2/6cIGFi1te0seNXM0sCsIt9WGW95rGmWi9iqzLFJOQpJ2FY" +
    "p3P67wLqgstjDkAKiYY7kzwVCVNglwQ7Ggn5ogwDocDQJoJMZsnmKrwhUDFTMxIcNtTgwFvE6nNAEWh6qok6VBF5y+BMYtagKUWZGvhaa" +
    "xFXoUlnhAUgCFgIB0UEg0LQcIAHC7iFQVCgARzSgRqLWgkggWSHAbAjYjAqhSQwgTIKIKINWLQNYsJciUjCEVDvFsHmUpLicj6E9DaDuF" +
    "vJoYxkmkfpvGCZ50H2hKHH6ul8jBMCxjxIUSEzj/UCvV54kKHyVRfzgR00BbOkvx6n4j0azPnqeRKQQ9KIUnVKvL6IQ9GHEQUkRRG+fhz" +
    "nQgywj1DlKE3D/ORC0AZRBSRGcf6cQ9GIIySVExM05EPVC2sqI5S7Gcc6EJdGnUcpPihM80DzRqFHSX4kIuw0iVl4Ps4TqNEnxQmeaCrd" +
    "OT20GFI/dMytYlKpkik1Y5uL57CgySXmtnUZhUzc3wIbyPM+ewYEN47VKHG6iFhy0qTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq" +
    "qqqqqqqqqqqqqqqqqqqqqqqqqqq";
